name: Daily Ruwya AI
on:
  schedule:
    # 06:30 Riyadh = 03:30 UTC
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python fetch_and_publish.py
